name: RdeRien

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: RdeRien
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Change this if your package is in a different directory

jobs:
  build :
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Composer
      uses: composer/setup-composer@v2

    - name: Verify Composer installation
      run: composer --version

    - name: Install dependencies
      run: composer install --no-dev --prefer-dist --no-interaction

    - name: Build artifact
      run: |
        mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        zip -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app.zip .

      name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app.zip
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
