name: PHP CI/CD to Azure Web App

on:
  push:
    branches:
      - main

env:
  AZURE_WEBAPP_NAME: your-app-name
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Change this if your package is in a different directory

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, zip

    # - name: Install Composer
    #   run: |
    #     curl -sS https://getcomposer.org/installer | php
    #     sudo mv composer.phar /usr/local/bin/composer

    # - name: Install dependencies
    #   run: composer install

    - name: Build artifact
      run: |
        mkdir -p ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
        zip -r ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app.zip .

    # - name: Deploy to Azure Web App
    #   uses: azure/webapps-deploy@v2
    #   with:
    #     app-name: ${{ env.AZURE_WEBAPP_NAME }}
    #     package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/app.zip
    #     publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
